name: common
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  dartx: ^1.2.0
  rxdart: ^0.27.7
  synchronized: ^3.1.0
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.3.7
  flutter_hooks: ^0.20.0
  flutter_portal: ^1.1.4
  visibility_detector: ^0.4.0+2

  animated_size_and_fade: ^3.0.1
  document_file_save_plus: ^2.0.0
  saver_gallery: ^2.0.1
  hooks_riverpod: ^2.3.8
  photo_view: ^0.14.0
  riverpod: ^2.3.7
  riverpod_annotation: ^2.1.2
  sliver_tools: ^0.2.12
  syncfusion_flutter_core: ^22.2.10
  syncfusion_flutter_pdfviewer: ^22.2.10
  url_launcher: ^6.1.12
  animated_list_plus: ^0.5.1
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner:
  custom_lint:
  freezed: ^2.4.1
  riverpod_generator: ^2.2.6
  riverpod_lint: ^2.0.1

dependency_overrides:
  webview_flutter_android:
    git: git@codeup.aliyun.com:6240585956f85235f7dd77d1/app/webview_flutter_android-3.9.2.git

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
